spring.application.name=studentCrud

server.port=8090

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/studentCrud
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
spring.output.ansi.enabled=ALWAYS
logging.level.root=INFO
logging.level.com.student.studentCrud.serviceImp=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %highlight([%level]) %green(%logger{36}) - %msg%n

# Swagger
springdoc.api-docs.version=OPENAPI_3_0

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC';